### ISSUE TITLE
No teams are shown

### ISSUE THREAD

**Issue by fire** [godotengine/godot-team-reports#17]
<img width="1754" alt="Screen Shot 2022-07-13 at 4 21 10 PM" src="https://user-images.githubusercontent.com/32321/178853188-786ec490-290f-43e9-b02b-721eb4b3ef44.png">

**Comment by YuriSizov** [comment]
Yes, I know, it's an issue with GitHub's GraphQL API which we are trying to solve.

**Comment by YuriSizov** [comment]
Fixed everything for now, should be back to its former glory :)
